version: "3.8"
services:
  event_mgmt_mssql:
    container_name: event_mgmt_mssql
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    ports:
      - "1433:1433"
    volumes:
      - ./database:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
  # event_mgmt_minio:
  #   container_name: event_mgmt_minio
  #   image: minio/minio
  #   volumes:
  #     - ./minio:/data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   command: server --console-address ":9001" /data
